### ISSUE TITLE
Utilize composer to manage dependancies?

### ISSUE THREAD

**Issue by jfcherng** [the-turk/flarum-diff#1]
I am not using Flarum but obviously Flarum uses Composer and so does this plugin.

Wouldn't move [this](https://github.com/the-turk/flarum-diff/blob/b68c0b06438a13b964b76e2485e28f16631501eb/resources/assets/composer.json#L3) to [the top level composer.json](https://github.com/the-turk/flarum-diff/blob/b68c0b06438a13b964b76e2485e28f16631501eb/composer.json#L23-L25) and remove [this](https://github.com/the-turk/flarum-diff/blob/b68c0b06438a13b964b76e2485e28f16631501eb/src/Listeners/PostActions.php#L4) and [this](https://github.com/the-turk/flarum-diff/blob/b68c0b06438a13b964b76e2485e28f16631501eb/src/Listeners/AddDiffRelationship.php#L4) results in a better dependency management practice? And then you don't have to add `vendor/` directory to your repo as well.

I randomly check an official extension, [flarum/auth-twitter](https://github.com/flarum/auth-twitter/blob/987b9c3bd2c6c80f509d5a1cfb523543521fa933/composer.json#L19) just uses the standard/common way to manage PHP component dependencies like other PHP applications.

**Comment by the-turk** [comment]
Yeah it's actually released as work-in-progress, still some issues waiting to be solved:
https://discuss.flarum.org/d/22755-mithril-related-issues-on-poststream-items

I didn't announce it to community yet but thanks for the info they probably will be done in 0.1.0-beta.2

**Comment by jfcherng** [comment]
By the way, since you utilize jfcherng/php-diff 6.4.3 feature/fix, the min version should be `^6.4.3` (not `^6.3`).

**Comment by the-turk** [comment]
i've just uploaded this version to show Flarum devs actually so they can see what's going on with the source code (mainly the js part of it) 😅 thanks again.

**Comment by the-turk** [comment]
closing this for now, feel free to re-open when you have any other request when 0.1.0-beta.2 is released.
