### ISSUE TITLE
No Revisions Error

### ISSUE THREAD

**Issue by theportablegeek** [the-turk/flarum-diff#5]
I am running into similar error as other on Flarum Discuss where I am getting a 404 error on Diffs and they show no revisions for some reason.

I have followed the steps outlined here https://discuss.flarum.org/d/22779-diff-for-flarum to resolve the issue including the remove, require and migrate but not change ...

Any help would be appreciated :)

**Comment by theportablegeek** [comment]
Found the solution! It doesnt play nice with the Nickname changer!

**Comment by the-turk** [comment]
Hi, which version are you using? There were some PHP related typos on beta 6 and i think i fixed them on beta 7.

**Comment by theportablegeek** [comment]
@the-turk I am using beta 7 but it looks like the issue is with this extension https://github.com/Dem13n/nickname-changer

**Comment by the-turk** [comment]
Hmmm, i've never used it actually. I'm planning to release a new version of the Diff this week and I'will definitely test these two together. Thanks for the report.

**Comment by theportablegeek** [comment]
Thank you so much! I also wanted to say this is an incredible extension - and is a huge game changer for my organization, allowing us to move from multiple platforms directly to Flarum for all our internal documentation (turning Flarum into a Wiki). Keep up the great work!

**Comment by the-turk** [comment]
Thank you and please also keep in mind that v2 is a fresh start and will remove previous diffs -it'll worth it though 😉

**Comment by the-turk** [comment]
For future readers: Diff conflicts with [dem13n/nickname-changer](https://discuss.flarum.org/d/21238-nickname-changer) package. Use [fof/username-request](https://discuss.flarum.org/d/20956-friendsofflarum-username-request) instead.
